dist: trusty
sudo: required
group: deprecated-2017Q4

language: go
go_import_path: github.com/opensds/opensds

go:
  - 1.9.x
  - tip

env:
  matrix:
  - TARGET=amd64
  # - TARGET=arm64
  # - TARGET=arm
  # - TARGET=386
  # - TARGET=ppc64le
  global:
  - secure: "IhEskTMEAsBNYTQCpDSlvDxIJK5cu1r2V"

before_install:
  - sudo apt-get install -y lvm2 tgt open-iscsi

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  exclude:
  # - go: tip
  #   env: TARGET=arm
  # - go: tip
  #   env: TARGET=arm64
  # - go: tip
  #   env: TARGET=386
  # - go: tip
  #   env: TARGET=ppc64le

install:
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
  # Build OpenSDS Controller source code
  - make all

script:
  - ./script/CI/coverage
  - ./script/CI/test

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out
  # Clean OpenSDS Controller built data
  - make clean
