dist: xenial
sudo: required

language: go
go_import_path: github.com/opensds/opensds

go:
  - 1.12.x
  - 1.13.x
  - tip

env:
  - TARGET=amd64
    GO111MODULE=on

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential gcc
  - sudo apt-get install -y librados-dev librbd-dev
  - sudo apt-get install -y lvm2 tgt open-iscsi
  - sudo docker pull p1c2u/openapi-spec-validator


matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  exclude:


install:
  # Build OpenSDS Controller source code
  - make all

script:
  - ./install/CI/coverage
  - ./install/CI/test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Clean OpenSDS Controller built data
  - make clean
