---
# Dummy variable to avoid error because ansible does not recognize the
# file as a good configuration file when no variable in it.
dummy:


###########
# GENERAL #
###########

workplace: /home/krej # Change this field according to your username, use '/root' if you login as root.

opensds_release: v0.1.4 # The version should be at least v0.1.4.
nbp_release: v0.1.0

# These fields are not suggested to be modified
opensds_download_url: https://github.com/opensds/opensds/releases/download/{{ opensds_release }}/opensds-{{ opensds_release }}-linux-amd64.tar.gz
opensds_tarball_url: /opt/opensds-{{ opensds_release }}-linux-amd64.tar.gz
opensds_dir: /opt/opensds-{{ opensds_release }}-linux-amd64
nbp_download_url: https://github.com/opensds/nbp/releases/download/{{ nbp_release }}/opensds-k8s-{{ nbp_release }}-linux-amd64.tar.gz
nbp_tarball_url: /opt/opensds-k8s-{{ nbp_release }}-linux-amd64.tar.gz
nbp_dir: /opt/opensds-k8s-{{ nbp_release }}-linux-amd64

opensds_config_dir: /etc/opensds
opensds_log_dir: /var/log/opensds

###########
# PLUGIN  #
###########

nbp_plugin_type: standalone # standalone is the default integration way, but you can change it to 'csi', 'flexvolume'

flexvolume_plugin_dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/opensds.io~opensds

###########
# GOLANG  #
###########

golang_release: 1.9.2

# These fields are NOT suggested to be modified
golang_tarball: go{{ golang_release }}.linux-amd64.tar.gz
golang_download_url: https://storage.googleapis.com/golang/{{ golang_tarball }}

###########
#CONTAINER#
###########

container_enabled: false
